// AWS Amplify configuration
// This will be auto-generated by Amplify CLI after deployment
// For development/non-Amplify environments, this config is disabled

// Only set amplifyConfig if we're actually deployed on Amplify
// The real config will be injected by Amplify during build
if (typeof window !== 'undefined' && window.location.hostname.includes('amplifyapp.com')) {
  window.amplifyConfig = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "WILL_BE_GENERATED_BY_AMPLIFY",
    "aws_cognito_region": "ap-northeast-1",
    "API": {
      "endpoints": [
        {
          "name": "tanabataAPI",
          "endpoint": "https://WILL_BE_GENERATED_BY_AMPLIFY.execute-api.ap-northeast-1.amazonaws.com/prod",
          "region": "ap-northeast-1"
        }
      ]
    },
    "Storage": {
      "AWSS3": {
        "bucket": "WILL_BE_GENERATED_BY_AMPLIFY",
        "region": "ap-northeast-1"
      }
    }
  };
}

// Note: After running 'amplify push', this file will be replaced
// with actual values from your AWS deployment