// AWS Amplify configuration
// This will be auto-generated by Amplify CLI after deployment
// For development/non-Amplify environments, this config is disabled

// AWS Amplify configuration will be auto-generated after running 'amplify push'
// This file is currently a placeholder and should not be used until 
// Lambda functions are properly deployed via Amplify CLI

// Uncomment and use real values only after successful 'amplify push' deployment
/*
if (typeof window !== 'undefined' && window.location.hostname.includes('amplifyapp.com')) {
  window.amplifyConfig = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "REAL_POOL_ID_FROM_AMPLIFY",
    "aws_cognito_region": "ap-northeast-1",
    "API": {
      "endpoints": [
        {
          "name": "tanabataAPI",
          "endpoint": "https://REAL_API_ID.execute-api.ap-northeast-1.amazonaws.com/prod",
          "region": "ap-northeast-1"
        }
      ]
    },
    "Storage": {
      "AWSS3": {
        "bucket": "REAL_BUCKET_NAME",
        "region": "ap-northeast-1"
      }
    }
  };
}
*/

// Note: After running 'amplify push', this file will be replaced
// with actual values from your AWS deployment