// AWS Amplify configuration
// This file will be auto-generated by Amplify CLI after deployment
// For now, it's a placeholder that shows the expected structure

window.amplifyConfig = {
  "aws_project_region": "ap-northeast-1",
  "aws_cognito_identity_pool_id": "WILL_BE_GENERATED",
  "aws_cognito_region": "ap-northeast-1",
  "API": {
    "endpoints": [
      {
        "name": "tanabataAPI",
        "endpoint": "https://YOUR_API_GATEWAY_URL.execute-api.ap-northeast-1.amazonaws.com/prod",
        "region": "ap-northeast-1"
      }
    ]
  },
  "Storage": {
    "AWSS3": {
      "bucket": "tanabata3d-tanzaku-data",
      "region": "ap-northeast-1"
    }
  }
};

// Note: After running 'amplify push', this file will be replaced
// with actual values from your AWS deployment